name = "cloudflare-playwright-scraper"
main = "src/index.ts"
compatibility_date = "2025-03-05"
workers_dev = true

compatibility_flags = ["nodejs_compat_v2"]

[browser]
binding = "MYBROWSER"
remote = true

[dev]
port = 9000